<?php

/**
 * Implements hook_init()
 */
function ajax_api_test_init() {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_js(drupal_get_path('module', 'ajax_api_test') . '/js/ajax_api_test.js' );
}

/**
 * Implements hook_menu()
 */
function ajax_api_test_menu(){
  $items['ajax/remote'] = array(
    'title' => 'Data',
    'page callback' => 'my_module_remote_ajax',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Ajax callback.
 *
 * Load remote information.
 */

function my_module_remote_ajax(){

  $html = 'Load View here';
  $selector = '#my-test-container';
  $messages = theme('status_messages');
  $commands = array();
  $commands[] = ajax_command_prepend('body', $messages);
  $commands[] = ajax_command_html($selector, $html);
  print ajax_render($commands);
  drupal_exit();


}
